name: fermer
description: Fermer Flutter project

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  animated_text_kit: ^4.2.2
  dio: ^5.1.2
  flutter_secure_storage: ^8.0.0
  flutter_launcher_icons: ^0.13.1
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.1
  shimmer: ^3.0.0
  flutter_slidable: ^3.0.0
  file_picker: ^5.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.4.4
  freezed: ^2.3.4
  json_serializable: ^6.7.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/icon.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/icons/icon.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  macos:
    generate: true
    image_path: "assets/icons/icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/

  fonts:
   - family: JetBrainsMono
     fonts:
       - asset: fonts/JetBrainsMono-Regular.ttf
       - asset: fonts/JetBrainsMono-Bold.ttf
         weight: 700

